
"use client"
import './globals.css'
import type { Metadata } from 'next'
import { SessionProvider } from 'next-auth/react'
import { Inter,Nunito } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const nunito = Nunito({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
subsets: ['latin' ]})

export const metadata: Metadata = {
  title: 'Xerocodee',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <SessionProvider session={undefined}>
    <html lang="en">
      <body className={nunito.className}>{children}</body>
    </html>
    </SessionProvider>
  )
}
