
import ClientComponent from '@/components/clientComponent'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Xerocodee',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}){
return(
  <>
  <ClientComponent>
    {children}
 </ClientComponent>
</>
)
}

